---
- name: determine installed PHP version
  shell: "php -v | head -1 | grep -o 'PHP 7.[0-9]' | sed -r 's/PHP //g'"
  register: php_version
  failed_when: "php_version.stdout == ''"

- name: determine PHP extension folder
  shell: "php -i | grep -o -m 1 'extension_dir .* =' | sed -r 's/extension_dir => //g' | sed -r 's/ =//g'"
  register: php_extension_dir
  failed_when: "php_extension_dir.stdout == 'xx'"
  ignore_errors: true

- name: set facts
  set_fact: >
    php_version="{{ php_version.stdout }}"
    php_extension_dir="{{ php_extension_dir.stdout }}"
    ioncube_tarfile="ioncube_loaders.tar.gz"
    
- name: download ion-cube-loader 64bit tar archive
  get_url: >
    url=https://downloads.ioncube.com/loader_downloads/ioncube_loaders_lin_x86-64.tar.gz
    dest=/tmp/{{ ioncube_tarfile }}
  when: ansible_machine == 'x86_64'

- name: unpack tar archive
  unarchive:
    src: "/tmp/{{ ioncube_tarfile }}"
    dest: "/tmp"
    copy: no

- name: install appropriate .so module
  command: cp "/tmp/ioncube/ioncube_loader_lin_{{ php_version }}.so" "{{ php_extension_dir }}/ioncube_loader_lin_{{ php_version }}.so"

- name: add file configuration Apache (for check)
  template: >
    src=ioncube.ini.j2
    dest=/etc/apache2/ioncube.ini

- name: add configuration Apache mod_php
  lineinfile:
    path: "/etc/php/7.4/apache2/php.ini"
    #line: 'zend_extension={{ php_extension_dir }}/ioncube_loader_lin_7.4.so'
    line: 'zend_extension=/usr/lib/php/20190902/ioncube_loader_lin_7.4.so'

 - name: apache2 reload
  systemd:
    name: apache2
    state: restarted
    
- name: add configuration PHP-FPM
  lineinfile:
    path: "/etc/php/7.4/fpm/php.ini"
    #line: 'zend_extension={{ php_extension_dir }}/ioncube_loader_lin_7.4.so'
    line: 'zend_extension=/usr/lib/php/20190902/ioncube_loader_lin_7.4.so'

- name: add configuration PHP CGI
lineinfile:
    path: "/etc/php/7.4/cgi/php.ini"
    #line: 'zend_extension={{ php_extension_dir }}/ioncube_loader_lin_7.4.so'
    line: 'zend_extension=/usr/lib/php/20190902/ioncube_loader_lin_7.4.so'

- name: php7.4-fpm restart
  systemd:
    name: php7.4-fpm-fpm
    state: restarted

#- name: link configuration
#  file:
#    src: /etc/apache2/ioncube.ini
#    #dest: /etc/php/7.4/apache2/conf.d/05-ioncube.ini
#    dest: /etc/php/{{ php_version }}/apache2/conf.d/05-ioncube.ini
#    state: link
    
- name: apache2 reload
  systemd:
    name: apache2
    state: restarted
